/// Flutter project context for CLI commands.
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

class ProjectContext {
  ProjectContext({
    required this.root,
    required this.isFlutterProject,
    this.applicationId,
    this.bundleIdentifier,
    this.hasFlowWidgetDependency = false,
  });

  final Directory root;
  final bool isFlutterProject;
  final String? applicationId;
  final String? bundleIdentifier;
  final bool hasFlowWidgetDependency;

  Directory get flowWidgetDir => Directory(p.join(root.path, 'flow_widget'));

  File get configFile => File(p.join(root.path, 'flow_widget.yaml'));

  File get pubspecFile => File(p.join(root.path, 'pubspec.yaml'));

  Directory get generatedDir =>
      Directory(p.join(flowWidgetDir.path, '.generated'));

  static Future<ProjectContext> discover({String? cwd}) async {
    final root = Directory(cwd ?? Directory.current.path);
    final pubspec = File(p.join(root.path, 'pubspec.yaml'));
    if (!await pubspec.exists()) {
      return ProjectContext(root: root, isFlutterProject: false);
    }

    final content = await pubspec.readAsString();
    final doc = loadYaml(content);
    if (doc is! YamlMap) {
      return ProjectContext(root: root, isFlutterProject: false);
    }

    final hasFlutter = doc.containsKey('flutter');
    final deps = doc['dependencies'];
    var hasFlowWidget = false;
    if (deps is YamlMap) {
      hasFlowWidget = deps.containsKey('flow_widget');
    }

    return ProjectContext(
      root: root,
      isFlutterProject: hasFlutter,
      applicationId: await _readAndroidApplicationId(root),
      bundleIdentifier: await _readIosBundleIdentifier(root),
      hasFlowWidgetDependency: hasFlowWidget,
    );
  }

  static Future<String?> _readAndroidApplicationId(Directory root) async {
    final gradle = File(p.join(root.path, 'android', 'app', 'build.gradle'));
    if (!await gradle.exists()) {
      final kts = File(p.join(root.path, 'android', 'app', 'build.gradle.kts'));
      if (await kts.exists()) {
        return _extractApplicationId(await kts.readAsString());
      }
      return null;
    }
    return _extractApplicationId(await gradle.readAsString());
  }

  static String? _extractApplicationId(String content) {
    final match = RegExp(
      r'''applicationId\s*=?\s*["']([^"']+)["']''',
    ).firstMatch(content);
    return match?.group(1);
  }

  static Future<String?> _readIosBundleIdentifier(Directory root) async {
    final pbx = File(
      p.join(root.path, 'ios', 'Runner.xcodeproj', 'project.pbxproj'),
    );
    if (!await pbx.exists()) return null;
    final content = await pbx.readAsString();
    final match = RegExp(
      r'PRODUCT_BUNDLE_IDENTIFIER = ([^;]+);',
    ).firstMatch(content);
    return match?.group(1)?.trim();
  }

  Future<Map<String, Object?>> readConfig() async {
    if (!await configFile.exists()) return {};
    final doc = loadYaml(await configFile.readAsString());
    if (doc is! YamlMap) return {};
    return _yamlToMap(doc);
  }

  Future<void> writeConfig(Map<String, Object?> config) async {
    final buffer = StringBuffer()
      ..writeln('# Generated by flow_widget CLI. Edit with care.')
      ..writeln()
      ..write(_mapToYaml(config));
    await configFile.writeAsString(buffer.toString());
  }
}

Map<String, Object?> _yamlToMap(YamlMap yaml) {
  return {
    for (final entry in yaml.entries)
      entry.key.toString(): _yamlValue(entry.value),
  };
}

Object? _yamlValue(Object? value) {
  if (value is YamlMap) {
    return _yamlToMap(value);
  }
  if (value is YamlList) {
    return value.map(_yamlValue).toList();
  }
  return value;
}

String _mapToYaml(Object? value, {int indent = 0}) {
  final pad = '  ' * indent;
  if (value is Map) {
    final buffer = StringBuffer();
    for (final entry in value.entries) {
      buffer.writeln('$pad${entry.key}:');
      buffer.write(_mapToYaml(entry.value, indent: indent + 1));
    }
    return buffer.toString();
  }
  if (value is List) {
    final buffer = StringBuffer();
    for (final item in value) {
      if (item is Map || item is List) {
        buffer.writeln('$pad-');
        buffer.write(_mapToYaml(item, indent: indent + 1));
      } else {
        buffer.writeln('$pad- ${_yamlScalar(item)}');
      }
    }
    return buffer.toString();
  }
  return '$pad${_yamlScalar(value)}\n';
}

String _yamlScalar(Object? value) {
  if (value == null) return 'null';
  if (value is bool || value is num) return value.toString();
  final text = value.toString();
  if (text.contains(':') || text.contains('#') || text.contains('\n')) {
    return '"$text"';
  }
  return text;
}
